export interface PaletteSwatch {
  bg: string
  surface: string
  accent: string
  text: string
}

export interface Palette {
  id: string
  name: string
  tag: string
  description: string
  isDark: boolean
  swatches: PaletteSwatch
  vars: Record<string, string>
}

export const PALETTES: Palette[] = [
  {
    id: 'oxford-navy',
    name: 'Oxford Navy & Gilded Amber',
    tag: 'Academic',
    description: 'Classic university library atmosphere with deep navy ink and gilded amber gold.',
    isDark: false,
    swatches: {
      bg: '#f7f9fc',
      surface: '#ffffff',
      accent: '#d97706',
      text: '#0a192f',
    },
    vars: {
      '--color-forest-ink': '#0a192f',
      '--color-highlighter-yellow': '#fbbf24',
      '--color-cream-paper': '#f7f9fc',
      '--color-pencil-gray': '#c6d3e3',
      '--color-whisper-gray': '#eef3f8',
      '--color-sticky-note-teal': '#bae6fd',
      '--color-sticky-note-mint': '#fde68a',
      '--color-sticky-note-blush': '#fed7aa',
      '--bg': '#f7f9fc',
      '--surface': '#ffffff',
      '--surface-cream': '#f7f9fc',
      '--surface-2': '#ecf1f7',
      '--surface-highlight': '#fde68a',
      '--border': '#c6d3e3',
      '--border-strong': '#0a192f',
      '--border-subtle': '#dbe4f0',
      '--text': '#0a192f',
      '--text-secondary': '#172a45',
      '--muted': '#536882',
      '--placeholder': '#7b8ea5',
      '--ring': '#0a192f',
      '--accent': '#d97706',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(217, 119, 6, 0.15)',
      '--primary': '#0a192f',
      '--primary-hover': '#162e4c',
      '--primary-light': '#fef3c7',
      '--primary-border': '#0a192f',
      '--good-bg': '#d1fae5',
      '--good-border': '#059669',
      '--good-text': '#064e3b',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#7f1d1d',
      '--warn-bg': '#fef3c7',
      '--warn-border': '#d97706',
      '--warn-text': '#78350f',
    },
  },
  {
    id: 'cream-forest',
    name: 'Cream & Forest Ink',
    tag: 'Editorial',
    description: 'Warm archival cream paper with deep evergreen ink and lemon highlighter accents.',
    isDark: false,
    swatches: {
      bg: '#fcfaf5',
      surface: '#ffffff',
      accent: '#ffe95c',
      text: '#1a3300',
    },
    vars: {
      '--color-forest-ink': '#1a3300',
      '--color-highlighter-yellow': '#ffe95c',
      '--color-cream-paper': '#fcfaf5',
      '--color-pencil-gray': '#b6b6b6',
      '--color-whisper-gray': '#f1f1f1',
      '--color-sticky-note-teal': '#a8e5e5',
      '--color-sticky-note-mint': '#d5f5c2',
      '--color-sticky-note-blush': '#f6d0ff',
      '--bg': '#fcfaf5',
      '--surface': '#ffffff',
      '--surface-cream': '#fcfaf5',
      '--surface-2': '#f5f2e9',
      '--surface-highlight': '#ffe95c',
      '--border': '#b6b6b6',
      '--border-strong': '#1a3300',
      '--border-subtle': '#e5dfd2',
      '--text': '#1a3300',
      '--text-secondary': '#2f4518',
      '--muted': '#5e6b54',
      '--placeholder': '#8b9682',
      '--ring': '#1a3300',
      '--accent': '#ffe95c',
      '--accent-text': '#1a3300',
      '--glow': 'rgba(255, 233, 92, 0.16)',
      '--primary': '#1a3300',
      '--primary-hover': '#264700',
      '--primary-light': '#ffe95c',
      '--primary-border': '#1a3300',
      '--good-bg': '#d5f5c2',
      '--good-border': '#1a3300',
      '--good-text': '#1a3300',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#991b1b',
      '--warn-bg': '#ffe95c',
      '--warn-border': '#1a3300',
      '--warn-text': '#1a3300',
    },
  },
  {
    id: 'kyoto-moss',
    name: 'Kyoto Bamboo & Moss',
    tag: 'Organic',
    description: 'Serene Japanese bamboo greens on organic washi paper with matcha accents.',
    isDark: false,
    swatches: {
      bg: '#f4f6f0',
      surface: '#ffffff',
      accent: '#84cc16',
      text: '#1b321c',
    },
    vars: {
      '--color-forest-ink': '#1b321c',
      '--color-highlighter-yellow': '#84cc16',
      '--color-cream-paper': '#f4f6f0',
      '--color-pencil-gray': '#b8c7b4',
      '--color-whisper-gray': '#eef2e9',
      '--color-sticky-note-teal': '#a7f3d0',
      '--color-sticky-note-mint': '#d9f99d',
      '--color-sticky-note-blush': '#fbcfe8',
      '--bg': '#f4f6f0',
      '--surface': '#ffffff',
      '--surface-cream': '#f4f6f0',
      '--surface-2': '#e8eee1',
      '--surface-highlight': '#d9f99d',
      '--border': '#b8c7b4',
      '--border-strong': '#1b321c',
      '--border-subtle': '#d6e2d3',
      '--text': '#1b321c',
      '--text-secondary': '#28482a',
      '--muted': '#5c735d',
      '--placeholder': '#7f9680',
      '--ring': '#274e2a',
      '--accent': '#84cc16',
      '--accent-text': '#1b321c',
      '--glow': 'rgba(132, 204, 22, 0.15)',
      '--primary': '#274e2a',
      '--primary-hover': '#36683a',
      '--primary-light': '#d9f99d',
      '--primary-border': '#1b321c',
      '--good-bg': '#dcfce7',
      '--good-border': '#15803d',
      '--good-text': '#14532d',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#b91c1c',
      '--bad-text': '#7f1d1d',
      '--warn-bg': '#fef08a',
      '--warn-border': '#a16207',
      '--warn-text': '#713f12',
    },
  },
  {
    id: 'nordic-slate',
    name: 'Nordic Slate & Fjord',
    tag: 'Minimalist',
    description: 'Crisp Scandinavian design with cool glacial blues and sharp slate ink.',
    isDark: false,
    swatches: {
      bg: '#f1f5f9',
      surface: '#ffffff',
      accent: '#0284c7',
      text: '#0f172a',
    },
    vars: {
      '--color-forest-ink': '#0f172a',
      '--color-highlighter-yellow': '#38bdf8',
      '--color-cream-paper': '#f1f5f9',
      '--color-pencil-gray': '#cbd5e1',
      '--color-whisper-gray': '#e2e8f0',
      '--color-sticky-note-teal': '#bae6fd',
      '--color-sticky-note-mint': '#bbf7d0',
      '--color-sticky-note-blush': '#e0e7ff',
      '--bg': '#f1f5f9',
      '--surface': '#ffffff',
      '--surface-cream': '#f1f5f9',
      '--surface-2': '#e2e8f0',
      '--surface-highlight': '#bae6fd',
      '--border': '#cbd5e1',
      '--border-strong': '#0f172a',
      '--border-subtle': '#e2e8f0',
      '--text': '#0f172a',
      '--text-secondary': '#1e293b',
      '--muted': '#64748b',
      '--placeholder': '#94a3b8',
      '--ring': '#0284c7',
      '--accent': '#0284c7',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(2, 132, 199, 0.14)',
      '--primary': '#0f172a',
      '--primary-hover': '#1e293b',
      '--primary-light': '#e0f2fe',
      '--primary-border': '#0f172a',
      '--good-bg': '#dcfce7',
      '--good-border': '#16a34a',
      '--good-text': '#14532d',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#991b1b',
      '--warn-bg': '#fef3c7',
      '--warn-border': '#d97706',
      '--warn-text': '#78350f',
    },
  },
  {
    id: 'tokyo-midnight',
    name: 'Tokyo Obsidian & Cyan',
    tag: 'Dark Mode',
    description: 'Sleek carbon dark mode with glowing electric cyan and deep obsidian panels.',
    isDark: true,
    swatches: {
      bg: '#090d16',
      surface: '#111827',
      accent: '#38bdf8',
      text: '#f0f6fc',
    },
    vars: {
      '--color-forest-ink': '#f0f6fc',
      '--color-highlighter-yellow': '#38bdf8',
      '--color-cream-paper': '#090d16',
      '--color-pencil-gray': '#1f293d',
      '--color-whisper-gray': '#161f30',
      '--color-sticky-note-teal': '#0284c7',
      '--color-sticky-note-mint': '#059669',
      '--color-sticky-note-blush': '#7c3aed',
      '--bg': '#090d16',
      '--surface': '#111827',
      '--surface-cream': '#111827',
      '--surface-2': '#192237',
      '--surface-highlight': '#0369a1',
      '--border': '#223049',
      '--border-strong': '#38bdf8',
      '--border-subtle': '#182337',
      '--text': '#f0f6fc',
      '--text-secondary': '#c9d1d9',
      '--muted': '#8b949e',
      '--placeholder': '#6e7681',
      '--ring': '#38bdf8',
      '--accent': '#38bdf8',
      '--accent-text': '#090d16',
      '--glow': 'rgba(56, 189, 248, 0.18)',
      '--primary': '#38bdf8',
      '--primary-hover': '#7dd3fc',
      '--primary-light': '#0c4a6e',
      '--primary-border': '#38bdf8',
      '--good-bg': '#064e3b',
      '--good-border': '#10b981',
      '--good-text': '#a7f3d0',
      '--bad-bg': '#450a0a',
      '--bad-border': '#ef4444',
      '--bad-text': '#fecaca',
      '--warn-bg': '#451a03',
      '--warn-border': '#f59e0b',
      '--warn-text': '#fde68a',
    },
  },
  {
    id: 'terracotta-sun',
    name: 'Tuscan Terracotta & Clay',
    tag: 'Warm Earth',
    description: 'Sunbaked Mediterranean clay with sand stationery and burnt sienna ink.',
    isDark: false,
    swatches: {
      bg: '#faf6f0',
      surface: '#ffffff',
      accent: '#ea580c',
      text: '#3c2415',
    },
    vars: {
      '--color-forest-ink': '#3c2415',
      '--color-highlighter-yellow': '#fdba74',
      '--color-cream-paper': '#faf6f0',
      '--color-pencil-gray': '#d4c2b2',
      '--color-whisper-gray': '#f2e8dc',
      '--color-sticky-note-teal': '#fed7aa',
      '--color-sticky-note-mint': '#ffedd5',
      '--color-sticky-note-blush': '#fde2e4',
      '--bg': '#faf6f0',
      '--surface': '#ffffff',
      '--surface-cream': '#faf6f0',
      '--surface-2': '#f3ece1',
      '--surface-highlight': '#fed7aa',
      '--border': '#d4c2b2',
      '--border-strong': '#9a3412',
      '--border-subtle': '#e9ded3',
      '--text': '#3c2415',
      '--text-secondary': '#5c351f',
      '--muted': '#82624e',
      '--placeholder': '#a48470',
      '--ring': '#ea580c',
      '--accent': '#ea580c',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(234, 88, 12, 0.14)',
      '--primary': '#9a3412',
      '--primary-hover': '#c2410c',
      '--primary-light': '#ffedd5',
      '--primary-border': '#9a3412',
      '--good-bg': '#ecfccb',
      '--good-border': '#65a30d',
      '--good-text': '#365314',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#7f1d1d',
      '--warn-bg': '#fef3c7',
      '--warn-border': '#b45309',
      '--warn-text': '#78350f',
    },
  },
  {
    id: 'swiss-monochrome',
    name: 'Swiss Studio & Bauhaus Red',
    tag: 'Modernist',
    description: 'High-contrast modernist black & white with bold Bauhaus red accents.',
    isDark: false,
    swatches: {
      bg: '#f9f9f9',
      surface: '#ffffff',
      accent: '#dc2626',
      text: '#111111',
    },
    vars: {
      '--color-forest-ink': '#111111',
      '--color-highlighter-yellow': '#ef4444',
      '--color-cream-paper': '#f9f9f9',
      '--color-pencil-gray': '#d4d4d4',
      '--color-whisper-gray': '#f1f1f1',
      '--color-sticky-note-teal': '#e5e5e5',
      '--color-sticky-note-mint': '#fee2e2',
      '--color-sticky-note-blush': '#f5f5f5',
      '--bg': '#f9f9f9',
      '--surface': '#ffffff',
      '--surface-cream': '#f9f9f9',
      '--surface-2': '#eeeeee',
      '--surface-highlight': '#fecaca',
      '--border': '#d4d4d4',
      '--border-strong': '#111111',
      '--border-subtle': '#e5e5e5',
      '--text': '#111111',
      '--text-secondary': '#2b2b2b',
      '--muted': '#666666',
      '--placeholder': '#999999',
      '--ring': '#dc2626',
      '--accent': '#dc2626',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(220, 38, 38, 0.14)',
      '--primary': '#111111',
      '--primary-hover': '#262626',
      '--primary-light': '#fee2e2',
      '--primary-border': '#111111',
      '--good-bg': '#dcfce7',
      '--good-border': '#16a34a',
      '--good-text': '#14532d',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#991b1b',
      '--warn-bg': '#fef3c7',
      '--warn-border': '#d97706',
      '--warn-text': '#78350f',
    },
  },
  {
    id: 'eucalyptus-sage',
    name: 'Apothecary Sage & Mint',
    tag: 'Calming',
    description: 'Soft botanical sage and silver eucalyptus mist for calm, eye-fatigue-free study.',
    isDark: false,
    swatches: {
      bg: '#f3f7f5',
      surface: '#ffffff',
      accent: '#059669',
      text: '#132a22',
    },
    vars: {
      '--color-forest-ink': '#132a22',
      '--color-highlighter-yellow': '#6ee7b7',
      '--color-cream-paper': '#f3f7f5',
      '--color-pencil-gray': '#bfd1c8',
      '--color-whisper-gray': '#eaf0ec',
      '--color-sticky-note-teal': '#a7f3d0',
      '--color-sticky-note-mint': '#d1fae5',
      '--color-sticky-note-blush': '#f2f7f4',
      '--bg': '#f3f7f5',
      '--surface': '#ffffff',
      '--surface-cream': '#f3f7f5',
      '--surface-2': '#e6eee9',
      '--surface-highlight': '#a7f3d0',
      '--border': '#bfd1c8',
      '--border-strong': '#194d3b',
      '--border-subtle': '#d8e4dd',
      '--text': '#132a22',
      '--text-secondary': '#204236',
      '--muted': '#567367',
      '--placeholder': '#799489',
      '--ring': '#059669',
      '--accent': '#059669',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(5, 150, 105, 0.14)',
      '--primary': '#194d3b',
      '--primary-hover': '#25634d',
      '--primary-light': '#d1fae5',
      '--primary-border': '#194d3b',
      '--good-bg': '#d1fae5',
      '--good-border': '#059669',
      '--good-text': '#064e3b',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#7f1d1d',
      '--warn-bg': '#fef9c3',
      '--warn-border': '#ca8a04',
      '--warn-text': '#713f12',
    },
  },
  {
    id: 'espresso-mocha',
    name: 'Velvet Espresso & Caramel',
    tag: 'Dark Mode',
    description: 'Warm roasted dark chocolate tones with smooth caramel and latte foam highlights.',
    isDark: true,
    swatches: {
      bg: '#14110f',
      surface: '#1c1714',
      accent: '#d4a373',
      text: '#f3ebe2',
    },
    vars: {
      '--color-forest-ink': '#f3ebe2',
      '--color-highlighter-yellow': '#d4a373',
      '--color-cream-paper': '#14110f',
      '--color-pencil-gray': '#3a3029',
      '--color-whisper-gray': '#27201c',
      '--color-sticky-note-teal': '#8c603b',
      '--color-sticky-note-mint': '#422817',
      '--color-sticky-note-blush': '#573c2a',
      '--bg': '#14110f',
      '--surface': '#1c1714',
      '--surface-cream': '#1c1714',
      '--surface-2': '#27201c',
      '--surface-highlight': '#8c603b',
      '--border': '#3d322a',
      '--border-strong': '#d4a373',
      '--border-subtle': '#2d241e',
      '--text': '#f3ebe2',
      '--text-secondary': '#ddcfc1',
      '--muted': '#9c8979',
      '--placeholder': '#736152',
      '--ring': '#d4a373',
      '--accent': '#d4a373',
      '--accent-text': '#14110f',
      '--glow': 'rgba(212, 163, 115, 0.16)',
      '--primary': '#d4a373',
      '--primary-hover': '#e3b98e',
      '--primary-light': '#422817',
      '--primary-border': '#d4a373',
      '--good-bg': '#14532d',
      '--good-border': '#22c55e',
      '--good-text': '#bbf7d0',
      '--bad-bg': '#450a0a',
      '--bad-border': '#ef4444',
      '--bad-text': '#fecaca',
      '--warn-bg': '#451a03',
      '--warn-border': '#f59e0b',
      '--warn-text': '#fde68a',
    },
  },
  {
    id: 'biarritz-coral',
    name: 'Biarritz Sunset & Coral',
    tag: 'Coastal',
    description: 'Breezy French coast sunset with soft rose sand and vibrant coral reef accents.',
    isDark: false,
    swatches: {
      bg: '#fff9f6',
      surface: '#ffffff',
      accent: '#f43f5e',
      text: '#3b1c1c',
    },
    vars: {
      '--color-forest-ink': '#3b1c1c',
      '--color-highlighter-yellow': '#fda4af',
      '--color-cream-paper': '#fff9f6',
      '--color-pencil-gray': '#e6cac5',
      '--color-whisper-gray': '#fdf0ec',
      '--color-sticky-note-teal': '#fecdd3',
      '--color-sticky-note-mint': '#ffe4e6',
      '--color-sticky-note-blush': '#fce7f3',
      '--bg': '#fff9f6',
      '--surface': '#ffffff',
      '--surface-cream': '#fff9f6',
      '--surface-2': '#faede8',
      '--surface-highlight': '#fecdd3',
      '--border': '#e6cac5',
      '--border-strong': '#be123c',
      '--border-subtle': '#fae1dc',
      '--text': '#3b1c1c',
      '--text-secondary': '#5c2a2a',
      '--muted': '#8a5858',
      '--placeholder': '#ad7b7b',
      '--ring': '#f43f5e',
      '--accent': '#f43f5e',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(244, 63, 94, 0.14)',
      '--primary': '#be123c',
      '--primary-hover': '#e11d48',
      '--primary-light': '#ffe4e6',
      '--primary-border': '#be123c',
      '--good-bg': '#ecfccb',
      '--good-border': '#65a30d',
      '--good-text': '#365314',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#7f1d1d',
      '--warn-bg': '#fef3c7',
      '--warn-border': '#d97706',
      '--warn-text': '#78350f',
    },
  },
  {
    id: 'matrix-phosphor',
    name: 'Matrix Terminal & Phosphor',
    tag: 'Dark Mode',
    description: 'Vintage monochrome CRT console phosphor green on deep obsidian space black.',
    isDark: true,
    swatches: {
      bg: '#080d09',
      surface: '#101811',
      accent: '#22c55e',
      text: '#dcfce7',
    },
    vars: {
      '--color-forest-ink': '#dcfce7',
      '--color-highlighter-yellow': '#4ade80',
      '--color-cream-paper': '#080d09',
      '--color-pencil-gray': '#1e2e21',
      '--color-whisper-gray': '#142017',
      '--color-sticky-note-teal': '#14532d',
      '--color-sticky-note-mint': '#052e16',
      '--color-sticky-note-blush': '#166534',
      '--bg': '#080d09',
      '--surface': '#101811',
      '--surface-cream': '#101811',
      '--surface-2': '#172419',
      '--surface-highlight': '#14532d',
      '--border': '#223625',
      '--border-strong': '#22c55e',
      '--border-subtle': '#192b1e',
      '--text': '#dcfce7',
      '--text-secondary': '#bbf7d0',
      '--muted': '#709f7a',
      '--placeholder': '#517a59',
      '--ring': '#22c55e',
      '--accent': '#22c55e',
      '--accent-text': '#080d09',
      '--glow': 'rgba(34, 197, 94, 0.18)',
      '--primary': '#22c55e',
      '--primary-hover': '#4ade80',
      '--primary-light': '#052e16',
      '--primary-border': '#22c55e',
      '--good-bg': '#052e16',
      '--good-border': '#22c55e',
      '--good-text': '#86efac',
      '--bad-bg': '#450a0a',
      '--bad-border': '#ef4444',
      '--bad-text': '#fecaca',
      '--warn-bg': '#451a03',
      '--warn-border': '#f59e0b',
      '--warn-text': '#fde68a',
    },
  },
  {
    id: 'provence-lavender',
    name: 'Provence Lavender & Violet',
    tag: 'Floral',
    description: 'French countryside violet and honey on delicate lilac-tinted stationery.',
    isDark: false,
    swatches: {
      bg: '#faf8fd',
      surface: '#ffffff',
      accent: '#9333ea',
      text: '#2b173b',
    },
    vars: {
      '--color-forest-ink': '#2b173b',
      '--color-highlighter-yellow': '#d8b4fe',
      '--color-cream-paper': '#faf8fd',
      '--color-pencil-gray': '#d7c8e8',
      '--color-whisper-gray': '#f4effa',
      '--color-sticky-note-teal': '#e9d5ff',
      '--color-sticky-note-mint': '#f3e8ff',
      '--color-sticky-note-blush': '#fae8ff',
      '--bg': '#faf8fd',
      '--surface': '#ffffff',
      '--surface-cream': '#faf8fd',
      '--surface-2': '#f0ebf7',
      '--surface-highlight': '#e9d5ff',
      '--border': '#d7c8e8',
      '--border-strong': '#581c87',
      '--border-subtle': '#e9e0f3',
      '--text': '#2b173b',
      '--text-secondary': '#43235d',
      '--muted': '#75598f',
      '--placeholder': '#997fb3',
      '--ring': '#9333ea',
      '--accent': '#9333ea',
      '--accent-text': '#ffffff',
      '--glow': 'rgba(147, 51, 234, 0.14)',
      '--primary': '#581c87',
      '--primary-hover': '#7e22ce',
      '--primary-light': '#f3e8ff',
      '--primary-border': '#581c87',
      '--good-bg': '#dcfce7',
      '--good-border': '#16a34a',
      '--good-text': '#14532d',
      '--bad-bg': '#fee2e2',
      '--bad-border': '#dc2626',
      '--bad-text': '#7f1d1d',
      '--warn-bg': '#fef3c7',
      '--warn-border': '#d97706',
      '--warn-text': '#78350f',
    },
  },
]

export function getPalette(id?: string): Palette {
  return PALETTES.find((p) => p.id === id) ?? PALETTES[0]
}

export function applyPalette(paletteId?: string) {
  const p = getPalette(paletteId)
  if (typeof document === 'undefined') return
  const root = document.documentElement
  root.setAttribute('data-palette', p.id)
  root.style.colorScheme = p.isDark ? 'dark' : 'light'
  for (const [key, val] of Object.entries(p.vars)) {
    root.style.setProperty(key, val)
  }
}
